name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x # Ensure this targets .NET 8

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Publish to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: YOUR_AZURE_APP_NAME
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
