name: Build, Test, and Deploy .NET 8 Project

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-and-setup-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: List Installed .NET SDKs
        run: dotnet --list-sdks

      - name: Setup .NET SDK (Ensure .NET 8.0)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Verify Installed .NET Version
        run: dotnet --version

      - name: Build Project
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish Project
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: BlazorAppRG     # Replace with your Azure App Service name
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
